version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: TEST@123
      MYSQL_DATABASE: expenses_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expenseapp_nw
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTEST@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  java_app:
    build:
      context: .
    container_name: expenseapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/expenses_tracker?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TEST@123
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    networks:
      - expenseapp_nw
    restart: always

networks:
  expenseapp_nw:

volumes:
  mysql_data:
